secretGenerator:
- name: mysql-info
  literals:
  - user-wp=wordpress_user
  - password-wp=efficaceetpascher
  - db-wp=wordpress_db
- name: mysql-pass
  literals:
  - password=root_password

resources:
  # - 'nginx/nginx.yaml'
  # - 'wordpress/wordpress.yaml'
  # - 'phpmyadmin/phpmyadmin.yaml'
  # - 'ingress/ingress.yaml'
  # - 'mysql/mysql.yaml'
  - 'influxdb/influxdb.yaml'
  - 'telegraf/telegraf.yaml'
  # - 'grafana/grafana.yaml'
  # - 'ftps/ftps.yaml'