secretGenerator:
- name: wp-info
  literals:
  - host=mysql
  - user=wordpress_user
  - password=efficaceetpascher
  - db=wordpress_db
- name: pma-info
  literals:
  - host=mysql
  - user=pma
  - password=cestlamafquejprefere
- name: mysql-pass
  literals:
  - password=root_password

resources:
  - 'nginx/nginx.yaml'
  - 'wordpress/wordpress.yaml'
  - 'phpmyadmin/phpmyadmin.yaml'
  - 'ingress/ingress.yaml'
  - 'mysql/mysql.yaml'
  - 'influxdb/influxdb.yaml'
  - 'telegraf/telegraf.yaml'
  - 'grafana/grafana.yaml'
  - 'ftps/ftps.yaml'