apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      nodePort: 3000
  selector:
    app: grafana
  type: NodePort
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: grafana
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: custom-grafana:1
        imagePullPolicy: Never
        name: grafana
        volumeMounts:
        - name: config-volume-datasources
          mountPath: /grafana/conf/provisioning/datasources
        - name: config-volume-dashboards
          mountPath: grafana/conf/provisioning/dashboards
      volumes:
        - name: config-volume-datasources
          configMap:
            name: grafana-datasources-config
        - name: config-volume-dashboards
          configMap:
            name: grafana-dashboards-config