apiVersion: v1
kind: Service
metadata:
  name: ssh
  labels:
    app: ssh
spec:
  ports:
    - port: 22
      nodePort: 22
  selector:
    app: ft_services
    run: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
      run: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        run: nginx
    spec:
      containers:
      - name: nginx
        image: custom-nginx:1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22


