apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: "NodePort"
  selector:
      run: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wodpress-deployment
spec:
  selector:
    matchLabels:
      app: ft_services
      run: wordpress
  template:
    metadata:
      labels:
        app: ft_services
        run: wordpress
    spec:
      containers:
      - name: wordpress-pod
        image: custom-wordpress:1
        imagePullPolicy: Never
