apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
      app: ftps
  ports:
    - name: in1
      port: 21
      targetPort: 21
      nodePort: 21
    - name: in2
      port: 20
      targetPort: 20
      nodePort: 20
    - name: out
      port: 20000
      targetPort: 20000
      nodePort: 20000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: custom-ftps:1
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20


